
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saida0512
      POSTGRES_DB: notes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:saida0512@db:5432/notes
      SECRET_KEY: sadoka78
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
